# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spectackle < Formula
  desc "Token-efficient, spec-driven MCP server for cross-language codebases"
  homepage "https://github.com/jxsl13/spectackle"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jxsl13/spectackle/releases/download/v0.2.1/spectackle_darwin_amd64.tar.gz"
      sha256 "b81dbc14aca8181ad71147db56656c8a3631ff8c85228548a122db97afe8e0f3"

      define_method(:install) do
        bin.install "spectackle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jxsl13/spectackle/releases/download/v0.2.1/spectackle_darwin_arm64.tar.gz"
      sha256 "8e37e9f1bb5f3183b63889f07ccc780d57cd7f5bc5178428b96f1b2efbe6332b"

      define_method(:install) do
        bin.install "spectackle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jxsl13/spectackle/releases/download/v0.2.1/spectackle_linux_amd64.tar.gz"
      sha256 "47cc4e2e435a3dec20ea8247995fc10c8ff93591972fab8aacd4f4ff8e1959de"
      define_method(:install) do
        bin.install "spectackle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jxsl13/spectackle/releases/download/v0.2.1/spectackle_linux_arm64.tar.gz"
      sha256 "abfd2ffe9d9732cd34625f89b98afc7de9af48a61cbe610719ae2ba3de24f7fd"
      define_method(:install) do
        bin.install "spectackle"
      end
    end
  end

  test do
    system "#{bin}/spectackle", "version"
  end
end
